name: Publish JSON ARM template

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths:
      - '**.bicep'
  workflow_dispatch:

env:
  out_dir: public
  main_bicep_file: main_parent.bicep
  publish_branch: json_template

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        run: |
          mkdir ./${{ env.out_dir }}
          az bicep build --file ${{ env.main_bicep_file }} --outdir ${{ env.out_dir }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.out_dir }}
          publish_branch: ${{ env.publish_branch }}